trigger:
  batch: true
  branches:
    include:
      - master

pr: none

jobs:
  - job: CDelivery
    pool:
      vmImage: "windows-latest"
    steps:
      - task: UseDotNet@2
        displayName: "Install .NET"
        inputs:
          version: 7.0.x
      - task: DotNetCoreCLI@2
        inputs:
          command: "run"
          projects: "**/AvaloniaTemplate.Packager.csproj"
          arguments: "--cdelivery"
      - task: CopyFiles@2
        inputs:
          SourceFolder: "AvaloniaTemplate.Fluent.Desktop/bin/dist/cdelivery/"
          contents: "**"
          targetFolder: $(Build.ArtifactStagingDirectory)
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: $(Build.ArtifactStagingDirectory)
          artifactName: AvaloniaBuildOutputs
